source :rubygems

path '../'

gemspec

platforms :jruby do
  gem 'jdbc-sqlite3', '~> 3.7.2'
  gem 'do_jdbc',      '0.10.14'
end

group :development do # Development dependencies (as in the gemspec)
  gem 'rake'
end
